//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoiDichVuXemPhim
    {
        public int MaGoiDichVu { get; set; }
        public string TenGoiDichVu { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public Nullable<int> MaKhuyenMai { get; set; }
    
        public virtual KhuyenMaiGoiXemPhim KhuyenMaiGoiXemPhim { get; set; }
    }
}
