//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoiDichVuQuangCao
    {
        public int MaQuangCao { get; set; }
        public string TenDichVuQuangCao { get; set; }
        public Nullable<decimal> GiaTien { get; set; }
        public Nullable<int> MaNhaQuangCao { get; set; }
        public Nullable<int> MaGiaoDich { get; set; }
        public Nullable<int> MaKhuyenMai { get; set; }
    
        public virtual ThanhToan ThanhToan { get; set; }
        public virtual KhuyenMaiGoiXemPhim KhuyenMaiGoiXemPhim { get; set; }
        public virtual NhaQuangCao NhaQuangCao { get; set; }
    }
}
