//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaQuangCao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaQuangCao()
        {
            this.GoiDichVuQuangCaos = new HashSet<GoiDichVuQuangCao>();
        }
    
        public int MaNhaQuangCao { get; set; }
        public string TenNhaQuangCao { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> MaGiaoDich { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoiDichVuQuangCao> GoiDichVuQuangCaos { get; set; }
        public virtual ThanhToan ThanhToan { get; set; }
        public virtual ThanhToan ThanhToan1 { get; set; }
    }
}
